### PR TITLE
added user-agent header to search request to fix 403 issue

### PR DESCRIPTION
**Pull request by bigjca**
The how long to beat search call seems to result in a 403 error if the user-agent request header is 'axios' which axios appears to set by default. I added the user agent header in the same way it is being done on the detailHtml call and it seems to work.

### CODE REVIEW

**Comment by alptonguc** [comment]
I changed src/main/hltbsearch.ts 80th line from node modules in my project added new user agents (Mozilla/5.0) but still getting 403. Am i missing something else?

**Comment by bigjca** [comment]
Yep, sorry I forgot to push a few other changes. If you are modifying in your local node modules you'll need to add the user agent header to [dist/main/hltbsearch.js](https://github.com/ckatzorke/howlongtobeat/pull/54/commits/56e953a821e1badf7c254e02c0df4bce0293d5b5#diff-f8f4e5019ff35e0aa489530e3f03bb979aa9137ed8bb0c8e301a05b97315236eR84)

**Comment by alptonguc** [comment]
Yep. I missed that one too. Now works as expected, Thanks.

**Comment by ckatzorke** [comment]
Thank you @bigjca, I just added the line (since I obviously only forgot to set the user-agent properly when searching).

I will close this PR, since you must not modify the js files in dist folder (they are generated by tsc). I am still lacking to convert this to github actions, making the build process automated (as well as the publish process).

v1.7.1 is now available, please test and enjoy
https://www.npmjs.com/package/howlongtobeat

**Pull request closed without merging**
